test and run docker compose

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -16,3 +16,31 @@ jobs:
     runs-on: [self-hosted, linux]
 
     steps:
+
+      - uses: actions/checkout@v4
+
+      - name: Set up JDK 11 for x64
+        uses: actions/setup-java@v3
+        with:
+          java-version: '11'
+          distribution: 'temurin'
+          architecture: x64
+
+      - name: Grant execute permission for gradlew
+        run: chmod +x gradlew
+
+      - name: build with Gradle
+        run: ./gradlew --info build
+
+      - name: Test with Gradle
+        run: ./gradlew --info test
+
+      # Todo: 환경변수 세팅 해줘야함
+      - name: Check Test Status
+        run: |
+          if [[ "$?" -eq "0" ]]; then
+            echo "Tests passed, restarting Docker container..."
+            docker-compose up -d
+          else
+            echo "Tests failed, Docker container will not be restarted."
+          fi
